# base parameters
n_agents: 5
m_informed: 2
share_cost: 1.0
starting_capital: 0.0
max_rounds: 2
seed: 42

# displayable (for agents) names
#display_names_file:
#display_names_random: false

# LLM and sampling
# model, api_type: fake - for pre-coded run
model: llama3.2:3b
api_type: ollama
temperature: 0.7
top_p: 1.0

# Prompt template, matcher logic, payment mode
template_version: v1_baseline
matcher: first_come
payment_mode: teacher_pays
